// Re-export all contract types from the accounting index (single source of truth)
export {
  ContractStatus,
  SignerRole,
  SignatureType,
  ContractStyleTheme,
  type ContractCategory,
  type ContractResponse,
  type CreateContractInput,
  type UpdateContractInput,
  type SignContractInput,
  type SendContractInput,
  type CreateContractResponse,
  type UpdateContractResponse,
  type SignContractResponse,
  type SendContractResponse,
  type GetContractResponse,
  type GetContractsResponse,
  type GetContractsByOrganizationIdResponse,
  type VerifyTokenInput,
  type VerifyTokenResponse,
  type VerifyTokenGraphQLResponse,
  type ContractTemplateSummary,
  type ContractTemplateDetail,
  type ContractTemplateSection,
  type ContractTemplateVariable,
  type ContractSignatureEntry,
  type ContractSignatureBlock,
  type GetContractTemplatesResponse,
  type GetContractTemplateResponse,
} from './accounting/index.js';